// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using multi_hosp_demo.JobQueues;

#nullable disable

namespace multihospdemo.Migrations
{
    [DbContext(typeof(JobDbContext))]
    [Migration("20230831074528_jobrecord1")]
    partial class jobrecord1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("multi_hosp_demo.JobQueues.JobRecord", b =>
                {
                    b.Property<string>("QueueID")
                        .HasColumnType("text")
                        .HasColumnName("queue_id");

                    b.Property<DateTime>("ExecuteAfter")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("execute_after");

                    b.Property<DateTime>("ExpireOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expire_on");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_complete");

                    b.Property<JsonElement>("JCommand")
                        .HasColumnType("jsonb")
                        .HasColumnName("j_command");

                    b.HasKey("QueueID");

                    b.ToTable("job_record", "mrqcs");
                });
#pragma warning restore 612, 618
        }
    }
}
